# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: twitch.py
site_description: >
  A Python library designed to interact with Twitch's API and provide real-time event handling 
  through WebSocket EventSub. It simplifies asynchronous operations, making it easy to integrate 
  Twitch functionalities into your Python projects.
# GitHub repository
repo_url: https://github.com/MrSniFo/twitch.py
repo_name: twitch.py
copyright: Copyright (c) 2024-present Snifo

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MrSniFo

theme:
  name: 'material'
  icon:
    logo: material/twitch
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/eye
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  features:
    - navigation.path
    - navigation.tabs
    - navigation.prune
    - navigation.tracking
    - content.code.copy
    - content.tabs.link

nav:
  - Getting started:
      - 'index.md'
      - Setup: 'setup.md'
      - Quickstart: 'quickstart.md'
      - Questions: 'questions.md'
  - Reference:
      - Client: 'reference/client.md'
      - Classes: 'reference/classes.md'
      - Exceptions: 'reference/exceptions.md'
      - Types: 'reference/types.md'
      - Debug: 'reference/debug.md'
  - Events Reference:
      - 'events/index.md'
      - Events: 'events/events.md'
      - Types: 'events/types.md'
  - Extensions:
      - Bot:
          - 'ext/bot/index.md'
          - Bot: 'ext/bot/bot.md'
          - Events: 'ext/bot/events.md'
      - Oauth:
          - 'ext/oauth/index.md'
          - Oauth: 'ext/oauth/oauth.md'
          - Events: 'ext/oauth/events.md'
          - Enums: 'ext/oauth/enums.md'
markdown_extensions:
  - def_list
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - codehilite
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:

          import:
            - https://docs.python.org/3/objects.inv
          paths: [.., ../twitch/ext]
          options:
            inherited_members: true
            show_source: false
            show_root_toc_entry: true
            show_root_heading: true
            show_root_full_path: false
            members_order: source
            annotations_path: source
            docstring_style: numpy
            docstring_section_style: spacy
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_bases: true
            filters:
              - "!^_"
